apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "redis"
  labels:
    app: "redis"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "redis"
      annotations:
    spec:
      containers:
        - name: "redis"
          image: "redis:5.0.4"
          command: ["redis-server", "--appendonly", "yes"]
          volumeMounts:
          - mountPath: "/"
            name: redis-pv
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi