---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "chat-socket"
  namespace: "default"
  labels:
    app: "chat-socket"
    microservice: "riptides"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "chat-socket"
      microservice: "riptides"
  template:
    metadata:
      labels:
        app: "chat-socket"
        microservice: "riptides"
    spec:
      containers:
        - name: "chat-socket-sha256"
          image: "eu.gcr.io/riptides/chat-socket@sha256:a1db319c74c5830f36c2f8927620387cc1e9dd0a76290a556b28de0c9f7ff90d"
          env:
            - name: MYSQL_HOST
              value: 10.35.240.3
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: riptides-mysql-user-skye
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: riptides-mysql-user-skye
                  key: password
            - name: MYSQL_DATABASE
              value: riptides
            - name: REDIS_HOST
              value: 10.0.14.156
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
            - name: RIPTIDES_API_HOST
              value: http://10.0.0.213
            - name: RIPTIDES_HOST
              value: http://riptides.io
          volumeMounts:
            - name: keys
              mountPath: "/app/key"
      volumes:
        - name: keys
          secret:
            secretName: riptides-api-keys
            items:
              - key: public.pem
                path: public.pem
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "chat-socket-hpa"
  namespace: "default"
  labels:
    app: "chat-socket"
    microservice: "riptides"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "chat-socket"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
