---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "riptides-api"
  namespace: "default"
  labels:
    app: "riptides-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "riptides-api"
  template:
    metadata:
      labels:
        app: "riptides-api"
        microservice: "riptides"
    spec:
      containers:
        - name: "api-sha256"
          image: "eu.gcr.io/riptides/api-go@sha256:416b3cd3612fb50f6bdab38f67f864ad385d8bce68269d1592e053e2b1d3c608"
          env:
            - name: DB_HOST
              value: 10.35.240.3
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: riptides-mysql-user-skye
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: riptides-mysql-user-skye
                  key: password
            - name: DB_NAME
              value: riptides
            - name: SPOTIFY_REDIRECT_URI
              value: https://riptides.io/settings
            - name: CORS_ALLOW_ORIGIN
              value: https://riptides.io/
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spotify-creds-secret
                  key: client_id
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spotify-creds-secret
                  key: client_secret
            - name: REDIS_HOST
              value: 10.0.14.156
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
            - name: CHAT_SOCKET_URL
              value: http://10.0.5.56
            - name: MAILGUN_DOMAIN
              value: mg.riptides.io
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailgun-secret
                  key: key
            - name: RIPTIDES_HOST
              value: https://riptides.io
            - name: GOOGLE_JSON_PATH
              value: /go/src/github.com/skyerus/riptides-go/config/google
            - name: FORGOT_PASSWORD_TPL
              value: /go/src/github.com/skyerus/riptides-go/assets/email/forgotPassword.html
            - name: JWT_PATH
              value: /go/src/github.com/skyerus/riptides-go/config/jwt
            - name: TZ
              value: Europe/London
          volumeMounts:
            - name: keys
              mountPath: /go/src/github.com/skyerus/riptides-go/config/jwt
            - name: google
              mountPath: /go/src/github.com/skyerus/riptides-go/config/google
      volumes:
        - name: keys
          secret:
            secretName: riptides-go-keys
            items:
            - key: private.key
              path: private.key
            - key: public.key
              path: public.key
        - name: google
          secret:
            secretName: storage-service-credentials
            items:
            - key: google.json
              path: google.json
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "riptides-api-hpa"
  namespace: "default"
  labels:
    app: "riptides-api"
    microservice: "riptides"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "riptides-api"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
