---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "riptides-ui"
  namespace: "default"
  labels:
    app: "riptides-ui"
    microservice: "riptides"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "riptides-ui"
      microservice: "riptides"
  template:
    metadata:
      labels:
        app: "riptides-ui"
        microservice: "riptides"
    spec:
      containers:
        - name: "ui-sha256"
          image: "eu.gcr.io/riptides/ui@sha256:10e48d63de14366b2598bcb1f760b134bb004362e865bd410ea2985155567d97"
          env:
            - name: CHAT_SOCKET_URL
              value: http://35.204.54.160:80
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "riptides-ui-hpa"
  namespace: "default"
  labels:
    app: "riptides-ui"
    microservice: "riptides"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "riptides-ui"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
