---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "riptides-ui"
  namespace: "default"
  labels:
    app: "riptides-ui"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "riptides-ui"
  template:
    metadata:
      labels:
        app: "riptides-ui"
    spec:
      containers:
        - name: "ui-sha256"
          image: "eu.gcr.io/riptides/ui@sha256:459abc37830302d0d175a890b43966567c03874e08f9872f6a1b47e6fc961993"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - name: riptides-ui
              containerPort: 80
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "riptides-ui-hpa"
  namespace: "default"
  labels:
    app: "riptides-ui"
    microservice: "riptides"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "riptides-ui"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
