---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "riptides-api"
  namespace: "default"
  labels:
    app: "riptides-api"
    microservice: "riptides"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "riptides-api"
      microservice: "riptides"
  template:
    metadata:
      labels:
        app: "riptides-api"
        microservice: "riptides"
    spec:
      containers:
        - name: "api-sha256"
          image: "eu.gcr.io/riptides/api@sha256:d9c30d3bf63ff0da27596116c7bdc52972dbacc7d122a66575b057d461c5c82a"
          env:
            - name: DB_HOST
              value: 10.35.240.3
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: riptides-mysql-user-skye
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: riptides-mysql-user-skye
                  key: password
            - name: DB_NAME
              value: riptides
            - name: JWT_MY_SECRET_KEY
              value: /app/config/jwt/private.pem
            - name: JWT_MY_PUBLIC_KEY
              value: /app/config/jwt/public.pem
            - name: JWT_MY_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: riptides-api-keys-secret
                  key: password
            - name: APP_SECRET
              value: 7e3ece4540f94b5d8919e1d91a2d846f
            - name: SPOTIFY_REDIRECT_URI
              value: https://riptides.io/settings
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spotify-creds-secret
                  key: client_id
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spotify-creds-secret
                  key: client_secret
            - name: REDIS_HOST
              value: 10.0.14.156
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
            - name: CHAT_SOCKET_URL
              value: http://10.0.5.56
            - name: APP_ENV
              value: prod
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", ". /app/deploy/deploy.sh"]
          volumeMounts:
            - name: keys
              mountPath: /app/config/jwt
            - name: google
              mountPath: /app/config/google
        - name: "nginx-api-sha256"
          image: "eu.gcr.io/riptides/nginx-api@sha256:00ce56ff9cd5a97cc3621b0b38fe02157b79c74eaf16248f68774f24cecef3cb"
      volumes:
        - name: keys
          secret:
            secretName: riptides-api-keys
            items:
            - key: private.pem
              path: private.pem
            - key: public.pem
              path: public.pem
        - name: google
          secret:
            secretName: storage-service-credentials
            items:
            - key: google.json
              path: google.json
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "riptides-api-hpa"
  namespace: "default"
  labels:
    app: "riptides-api"
    microservice: "riptides"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "riptides-api"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
