kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  labels:
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"