apiVersion: v1
kind: Service
metadata:
  labels:
    microservice: riptides-api
  name: riptides-api-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: riptides-api
  sessionAffinity: None
  type: NodePort
