apiVersion: v1
kind: Service
metadata:
  labels:
    microservice: riptides-chat
  name: chat-socket-service
  namespace: default
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"chat-socket"}}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: chat-socket
  sessionAffinity: ClientIP
  type: NodePort
